[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[deploy]
preDeployCommand = "npx prisma db push --accept-data-loss && npm run db:seed"
startCommand = "NODE_ENV=production npm run start"

